18
cqqqt/Task-Viewer-Backend pull request #47
Opened 2023-04-10 07:39 UTC by cichan02

2023-04-10 08:52 UTC, cichan02 commented
First of all merge https://github.com/cqqqt/Task-Viewer-Backend/pull/49

2023-04-10 11:21 UTC, h1alexbel requested changes
@cichan02 use 2 space indentation

2023-04-10 11:21 UTC, h1alexbel commented on src/test/java/com/taskviewer/api/postgres/PgTasksUnitTest.java
we don't tolerate empty lines
read: https://www.yegor256.com/2014/11/03/empty-line-code-smell.html

2023-04-10 11:21 UTC, h1alexbel commented on src/test/resources/application-test.yaml
> +  jpa:
@cichan02 we are not using any ORM here

2023-04-10 11:43 UTC, cichan02 commented
I see failed checks. Try to understand why failed.

2023-04-10 12:41 UTC, cichan02 commented
Я пока убрал интеграционный тест, чтобы смерджить. А потом уже разбираться.

2023-04-10 13:58 UTC, h1alexbel approved these changes

2023-04-10 14:00 UTC, h1alexbel requested changes
@cichan02 setup 2 space indentation

2023-04-10 14:20 UTC, cichan02 commented
Оно не меняется просто так!!!

2023-04-10 17:08 UTC, h1alexbel approved these changes

2023-04-10 17:09 UTC, h1alexbel commented
@cichan02 fix merge conflict

2023-04-10 17:09 UTC, cichan02 commented
Cheers 🥳

2023-04-10 17:50 UTC, cichan02 commented
@h1alexbel, finally it turns in git-branches-hell. I can't solve merge conflict without hard merge. Just merge 21, which bring #18 features too.

2023-04-10 19:18 UTC, h1alexbel approved these changes

2023-04-10 19:19 UTC, h1alexbel commented
@cichan02 fix the merge conflicts

2023-04-10 19:25 UTC, cichan02 commented
@h1alexbel solved all merge conflicts

2023-04-11 09:00 UTC, h1alexbel commented
@rultor merge

2023-04-11 09:00 UTC, h1alexbel approved these changes

2023-04-11 09:02 UTC, rultor commented
> @rultor merge 

@h1alexbel OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/31400-1502945627)

2023-04-11 09:03 UTC, merged

2023-04-11 09:03 UTC, h1alexbel commented
@cichan02 thanks