21
cqqqt/Task-Viewer-Backend pull request #48
Opened 2023-04-10 08:07 UTC by cichan02

2023-04-10 08:52 UTC, cichan02 commented
First of all merge https://github.com/cqqqt/Task-Viewer-Backend/pull/49

2023-04-10 11:19 UTC, h1alexbel requested changes

2023-04-10 11:19 UTC, h1alexbel commented on src/test/java/com/taskviewer/api/postgres/PgTasksIntegrationTest.java
> +	private PgTasks pgTasks;
use indentation spaces: 2

2023-04-10 11:19 UTC, h1alexbel commented on src/test/resources/application-test.yaml
> +      ddl-auto: create
@cichan02 we are not using any ORM here

we manage our schema using Liquibase instead

2023-04-10 12:46 UTC, cichan02 commented
Please view only https://github.com/cqqqt/Task-Viewer-Backend/pull/48/commits/1403df8766ed72e24df53044ff240a7c5b1898ef, because other one is from #18

2023-04-10 14:09 UTC, h1alexbel reviewed
@cichan02 use 2 space indentation instead of 4

2023-04-10 17:59 UTC, h1alexbel commented
@cichan02 please fix the merge conflict

2023-04-10 18:00 UTC, cichan02 commented
@h1alexbel merge https://github.com/cqqqt/Task-Viewer-Backend/pull/56

2023-04-10 18:19 UTC, h1alexbel approved these changes

2023-04-10 18:20 UTC, h1alexbel commented
@cichan02 fix merge conflict

2023-04-10 18:23 UTC, cichan02 commented
![image](https://user-images.githubusercontent.com/90219032/230966845-0301a125-0648-4cba-9fdc-f3f86666ef42.png)

2023-04-10 18:28 UTC, h1alexbel commented
@cichan02 just keep one, they're equal

2023-04-10 19:17 UTC, h1alexbel approved these changes

2023-04-10 19:17 UTC, h1alexbel commented
@cichan02 fix merge conflicts

2023-04-10 19:30 UTC, cichan02 commented
@h1alexbel fixed all merge conflicts

2023-04-11 09:12 UTC, cichan02 commented
@h1alexbel solved all merge conflict

2023-04-11 09:13 UTC, rultor commented
> @rultor merge

@cichan02 Thanks for your request; @h1alexbel please confirm this.

2023-04-11 11:18 UTC, h1alexbel requested changes
@cichan02 use 2 space indentation

2023-04-11 11:41 UTC, cichan02 commented
<img width="375" alt="Screenshot 2023-04-11 at 14 38 38" src="https://user-images.githubusercontent.com/90219032/231151872-60e9270f-2fb0-4e4e-9682-ba5ba1809074.png">
<img width="375" alt="Screenshot 2023-04-11 at 14 38 38" src="https://user-images.githubusercontent.com/90219032/231152147-c409f710-7a89-4939-bd45-f8a31dcb5cdc.png">
@h1alexbel see...

2023-04-11 12:13 UTC, h1alexbel approved these changes

2023-04-11 12:16 UTC, rultor commented
> @rultor merge

@h1alexbel OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/31402-1503220635)

2023-04-11 12:16 UTC, cichan02 commented
Hooray 🥳 for me!

2023-04-11 12:17 UTC, merged

2023-04-11 12:17 UTC, rultor commented
> @rultor merge

@h1alexbel Done! FYI, the full log is [here](https://www.rultor.com/t/31402-1503220635) (took me 1min)

2023-04-11 12:18 UTC, h1alexbel commented
@cichan02 thanks!